# 01- Numpy

In [2]:
import numpy as np

In [10]:
arr = np.array([1,3,5,7,9])
print(type(arr))

print(arr)

<class 'numpy.ndarray'>
[1 3 5 7 9]


In [11]:
print("배열의 원소는 %d개 입니다." % len(arr))

배열의 원소는 5개 입니다.


In [12]:
arr[4]

9

In [13]:
for i, v in enumerate(arr):

    print("%d번째 원소 >> %d" % (i,v))

0번째 원소 >> 1
1번째 원소 >> 3
2번째 원소 >> 5
3번째 원소 >> 7
4번째 원소 >> 9


In [14]:
arr2 = [100, 3.14, True, "dd", None,5j]
arr2

[100, 3.14, True, 'dd', None, 5j]

In [15]:
print(type(arr2[5]))
arr0 = arr2 *3
print(arr0)

<class 'complex'>
[100, 3.14, True, 'dd', None, 5j, 100, 3.14, True, 'dd', None, 5j, 100, 3.14, True, 'dd', None, 5j]


In [16]:
arr3 = np.array(arr2, dtype='str')
print(arr3)

['100' '3.14' 'True' 'dd' 'None' '5j']


In [17]:
mylist = list(arr3)
print(type(mylist))
mylist

<class 'list'>


['100', '3.14', 'True', 'dd', 'None', '5j']

## 기초 통계량 산출

### 1차원

In [18]:
myarr = np.array([98,23,65,77])
myarr

array([98, 23, 65, 77])

In [32]:
print("최대값:", np.max(myarr))
print("최소값:", np.min(myarr))
print("합계:", np.sum(myarr))
print("평균:", np.average(myarr))
print("분산:", np.var(myarr))
print("표준편차:", np.std(myarr))

최대값: 98
최소값: 23
합계: 263
평균: 65.75
분산: 748.6875
표준편차: 27.36215452043205


$d = y -\bar{y}$

$d^2$

$\Omega$ 모집단

$\mu$  모평균

$\sigma^2$ 모분산

$\sigma$ 모표준편차

$\bar{X}$ 표본평균

$s^2$  표본분산

$s$  표본표준편차

$n$ 표본크기

$\sum$ 합계

### NUMPY 배열간 연산

In [20]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([19,32,10,3,4])

#a = arr1+arr2
#b = arr1-arr2
#c = arr1*arr2
#d = arr1/arr2
#print(a)
#print(b)
#print(c)
#print(d)

a = np.add(arr1,arr2)
b = np.subtract(arr1,arr2)
c = np.multiply(arr1,arr2)
d = np.divide(arr1,arr2)
print(a)
print(b)
print(c)
print(d)


[29 47 30 28 34]
[ -9 -17  10  22  26]
[190 480 200  75 120]
[0.52631579 0.46875    2.         8.33333333 7.5       ]


In [8]:
# 2차원 배열 사칙연산
grade = np.array([
            [98, 72, 80, 64],
            [88, 90, 80, 72],
            [92, 88, 82, 76]
        ])
grade


array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82, 76]])

In [9]:
grade.shape

(3, 4)

In [11]:
grade.ndim

2

In [12]:
grade.dtype

dtype('int32')

In [14]:
# 각 열끼리 더함 (세로로 덧셈)
# 결과 타입은 numpy의 1차 배열 
s1 = np.sum(grade, axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([278, 250, 242, 212])

In [15]:
# 각 행끼리 더함
s2 = np.sum(grade, axis=1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([314, 330, 338])

## #04.  조건에 맞는 값 추출하기
### [1] 원하는 위치의 값 추출

In [21]:
grade = np.array([87,72,86,90,96])
grade

array([87, 72, 86, 90, 96])

In [22]:
boolarray = np.array([True, False, True, False,False])
boolarray

array([ True, False,  True, False, False])

In [23]:
result1 = grade[boolarray]
result1

array([87, 86])

In [24]:
result2 = grade[grade >= 80]
result2

array([87, 86, 90, 96])

In [25]:
result3 = grade[np.logical_and(grade >=85, grade <=90)]
result3

array([87, 86, 90])

In [26]:
result4 = grade[np.logical_or(grade <=80, grade >90)]
result4

array([72, 96])

# 도수분포

도수분포표
100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55

In [4]:
point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])
point

array([100,  91,  89,  86,  84,  79,  78,  77,  74,  71,  69,  66,  65,
        60,  58,  57,  55])

In [28]:
hist, bins = np.histogram(point,5)
print("구간별 데이터 수:",hist)
print("구간경계:", bins)

구간별 데이터 수: [4 4 4 3 2]
구간경계: [ 55.  64.  73.  82.  91. 100.]


In [29]:
s = len(hist)
for i in range(0, s):
    if i+1 <s:
        tpl = "%d이상 %d 미만: %d 개"
    else: 
        tpl = "%d이상 %d 이하: %d개"

    print(tpl % (bins[i], bins[i+1], hist[i]))

55이상 64 미만: 4 개
64이상 73 미만: 4 개
73이상 82 미만: 4 개
82이상 91 미만: 3 개
91이상 100 이하: 2개


데이터 구간을 직접 정의하기

In [5]:
hist, bins = np.histogram(point, [50,60,70,80,90,100])     
print("구간별 데이터 수:", hist)   # 절대도수: hist
print("구간별 경계:", bins)


구간별 데이터 수: [3 4 5 3 2]
구간별 경계: [ 50  60  70  80  90 100]


## #도수의 종류

In [7]:
# 상대도수
relative_freq = hist/np.sum(hist)
print(relative_freq)

# 누적도수 - 절대도수에서 자기 앞 도수를 모두 더한 값

cum_freq = []
previous = 0
for i in hist:
    previous += 1
    cum_freq.append(previous)
    
print(previous)




[0.17647059 0.23529412 0.29411765 0.17647059 0.11764706]
5
