# Numpy 형태 변환

In [22]:
import numpy as np

In [2]:
arr1 = np.arange(10,20)
print(arr1)
print(arr1.dtype)

[10 11 12 13 14 15 16 17 18 19]
int32


In [3]:
arr2 = np.asarray(arr1,dtype = 'bool')
print(arr2)
print(arr2.dtype)

[ True  True  True  True  True  True  True  True  True  True]
bool


In [4]:
arr3 = arr1.astype('float')
print(arr3)
print(arr3.dtype)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
float64


In [5]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 차원 변환

In [6]:
x = origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
y = origin.reshape(2, 2, 5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

## 차원 축소

In [25]:
origin = np.array([[0,1,2,3,4],
                   [5,6,7,8,9],
                   [10,11,12,13,14],
                   [15,16,17,18,19]
                   ])

In [9]:
origin.flatten() # 1차원 배열 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
origin.reshape(-1) # 1차원 배열 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
origin.ravel()  # 1차원 배열 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
o1 = origin.reshape(-1,1)
print(o1)
print(o1.ndim)  

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
2


In [12]:
origin.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [29]:
o2 = origin.reshape(1,-1)
print(o2)
print(o2.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
2


In [13]:
origin.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
rows, cols= origin.shape
rows, cols

(4, 5)

In [15]:
z = origin.reshape(rows*cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
y = origin.reshape(1, -1)  # 2차원 배열
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [24]:
arr = np.empty((1,2,2))  # 초기화되지 않는 값으로 배열 형성
arr

array([[[1., 1.],
        [1., 1.]]])

In [33]:
origin2 = origin.transpose()  # 행, 렬 전치
print(origin2)
print(origin2.shape)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
(5, 4)


In [3]:
# 모든 원소 0인 배열
print(np.zeros([3,4]))

# 모든 원소 1인 배열
print(np.ones([3,4]))

# 모든 원소가 특정값인 배열
print(np.full([3,4],5))

# 단위행렬
print(np.eye(4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# 랜덤배열

# 0부터 1 범위

print(np.random.rand(10))  # 원소수 10개
print(np.random.rand(4,3))  # 4행 3열 2차원 배열

# 주어진 범위 안 정수값
print(np.random.randint(0,9,10))  # 0부터 9까지 10개 원소
print(np.random.randint(0,9,(3,4,2))) # 0부터 9까지 3차원 배열


[0.07840862 0.25418171 0.08978212 0.13555974 0.48197529 0.46219758
 0.95918389 0.62063366 0.54673146 0.3481755 ]
[[0.2074083  0.67260712 0.98305121]
 [0.04562369 0.6273792  0.84722115]
 [0.2610602  0.34318345 0.62023262]
 [0.93577625 0.16091706 0.4716656 ]]
[3 2 1 6 1 0 5 4 6 0]
[[[6 5]
  [5 0]
  [3 0]
  [6 1]]

 [[0 6]
  [3 7]
  [2 2]
  [2 3]]

 [[5 3]
  [8 5]
  [0 3]
  [5 0]]]


In [7]:
# 표준정규분포

print(np.random.randn(10))  # 1차원
print(np.random.randn(4,3))  # 2차원

[-0.47731523 -0.38655125 -0.09624186  1.05888779 -0.85747902 -0.64800101
  0.06634262  0.2673378   1.09191844 -1.13900178]
[[ 0.33655106  1.61747902 -1.05049929]
 [-0.44696004 -0.76473436  0.07900723]
 [-1.72214886 -0.46958026  0.45276031]
 [-1.20025134  1.21437145  0.08890507]]


In [9]:
# 정규분포 직접 설정

print(np.random.normal(0, 1, 10))   # 평균 0, 표준편자 1 정규분포 10개원소
print(np.random.normal(0, 1, (4,3)))   # 평균 0, 표준편자 1 정규분포 4행 3열 2차원


[ 0.54789962  0.15550606  0.27020079  1.16494745  0.11413747  1.41308316
  0.99097529 -1.32984394  0.45708599 -0.01272286]
[[ 0.18704753  0.02019822 -0.60430615]
 [ 1.78946807 -1.29725059  0.69766368]
 [-1.63771992  0.51708442  0.27329627]
 [-0.7856777   0.77479481  1.87438145]]


In [19]:
# 랜덤값 고정

np.random.seed(123)
print(np.random.normal(0,1,(4,3)))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]
 [-0.8667404  -0.67888615 -0.09470897]]
